version: '2'
services:
  web:
    image: appsol/wp-cli-docker:apache-5.6
    container_name: wp-cli-docker_web
    domainname: wp-cli-docker.dev
    hostname: wp-cli-docker
    ports:
      - 80:80
    volumes:
      - ./public_html:/var/www/html
    links:
      - db:mysql
    depends_on:
      - db
    env_file: .env
  db:
    image: mariadb:latest
    container_name: wp-cli-docker_db
    ports:
      - 3306
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/import:/docker-entrypoint-initdb.d/
      - ./data/conf/:/etc/mysql/conf.d
    env_file: .env
