version: '2'
services:
  web:
    build: .
    image: wp-cli-docker:apache-5.6
    tty: true
    ports:
      - 80:80
    links:
      - db:mysql
    depends_on:
      - db
    environment:
      - DEV_NAME=wpdocker
      - DEV_DOMAIN=wpdocker.dev
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wpdocker
      - MYSQL_USER=wpdocker_user
      - MYSQL_PASSWORD=wpdocker_pass
      - WORDPRESS_TABLE_PREFIX=abc12_
      - WORDPRESS_SITE_TITLE=WP-Docker Test Site
      - WORDPRESS_ADMIN_USER=admin
      - WORDPRESS_ADMIN_PASS=letmein123
      - WORDPRESS_ADMIN_EMAIL=stuart@appropriatesolutions.co.uk
  db:
    image: mariadb:latest
    # container_name: wp-cli-docker_db
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wpdocker
      - MYSQL_USER=wpdocker_user
      - MYSQL_PASSWORD=wpdocker_pass
    # restart: on-failure
